Universe           = vanilla
Initialdir         = /sphenix/u/ryotaro/DirectPhotonAnalysis/Pi0Reconstruction/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 0
nEvents            = 20
job_offset         = 0
process_shift      = $(Process) + $(job_offset) 
output_directory = /sphenix/u/ryotaro/DirectPhotonAnalysis/Pi0Reconstruction/output/condor


Output             = $(output_directory)/condor_$(runnumber)_$INT(process_shift).out
Error              = $(output_directory)/condor_$(runnumber)_$INT(process_shift).err
Log                = /tmp/ryotaro/Pi0Reconstruction/condor_$(runnumber)_$INT(process_shift).log
Arguments          = "$INT(process_shift) $(nEvents)"
Queue 5000
