Universe           = vanilla
Initialdir         = /sphenix/user/ryotaro/DirectPhotonAnalysis/PhotonAnalysisTree
Executable         = /sphenix/user/ryotaro/DirectPhotonAnalysis/PhotonAnalysisTree/run_tree.sh
should_transfer_files = NO

PeriodicHold       = (NumJobStarts >= 1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
request_disk       = 4GB
Priority           = 20
job_lease_duration = 86400

n_jobs             = 5000
n_events           = 0
job_offset         = 0
process_id         = $(Process) + $(job_offset)
output_directory   = /sphenix/user/ryotaro/DirectPhotonAnalysis/PhotonAnalysisTree/output/condor

Output             = $(output_directory)/tree_$INT(process_id,%06d).out
Error              = $(output_directory)/tree_$INT(process_id,%06d).err
Log                = /tmp/ryotaro-PhotonAnalysisTree-tree_$INT(process_id,%06d).log
Arguments          = "$INT(process_id) $(n_events)"

Queue $(n_jobs)
