Universe           = vanilla
Initialdir         = /sphenix/user/ryotaro/DirectPhotonAnalysis/EventDisplay/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 0
job_offset         = 0
process_shift      = $(Process) + $(job_offset) 
output_directory = /sphenix/user/ryotaro/DirectPhotonAnalysis/EventDisplay/output/condor


Output             = $(output_directory)/condor_$(runnumber)_$INT(process_shift).out
Error              = $(output_directory)/condor_$(runnumber)_$INT(process_shift).err
Log                = /tmp/ryotaro_EventDisplay_condor_$(runnumber)_$INT(process_shift).log
Arguments          = "$INT(process_shift)"
Queue 1
