Universe           = vanilla
Initialdir         = /sphenix/u/ryotaro/DirectPhotonAnalysis/SinglePi0GunSimulation/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 6GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 0
nEvents            = 5
save_tree          = true
job_offset         = 0
process_shift      = $(Process) + $(job_offset) 
output_directory = /sphenix/u/ryotaro/DirectPhotonAnalysis/SinglePi0GunSimulation/output/condor


Output             = $(output_directory)/condor_$(runnumber)_$INT(process_shift).out
Error              = $(output_directory)/condor_$(runnumber)_$INT(process_shift).err
Log                = /tmp/ryotaro/SinglePi0GunSimulation/condor_$(runnumber)_$INT(process_shift).log
Arguments          = "$INT(process_shift) $(nEvents) $(save_tree)"
Queue 1
